# Travis CI configuration file for Lovefield.
language: node_js
node_js:
  - "4.3"

sudo: false

env:
  global:
    - secure: "VNerOdUQKati7WSKtgLoq857jAG+CKwCE7g+/XtipO5PbS4J92xttyZuYkCThZoSMYEl8EXvO22fw2tLb+5ylQLrFS/+9TO+kU1C7z5R0+JPDoeuDmNLkAbUyV0k2JLz4AI8o4kAJtghnLjUKRS8piJCKwwtdAoBwn8qJlq8Fgg="
    - secure: "oKPKrHsFRPUAkg7lt4NfKuE9DhENlWTbyr6oGtKkjQHrRU6LPl5iYa4X3Nr30o4ehvtRX2qcCXSxM5jTAuUalxv6ANbYKMFpnqERr7O6OoYUeOAopy+WtTwABXsNctuwn9AUUpGYaBB4Ipj1Hss+Ez/zCs55qZcE2XNli2GbQ2o="
    - secure: "OP4me/rh3JpfIe6ZKL9x3ARXqSfJTqvSdJcp2NsYJyJkj0Ptg1o67WCFYhlElhBRzGwBjJbDQ09SXkV6TMGP3HSTZeVyAlTktL11Lmveg2VMyEnpZ94puxq3GCWSEwA8C4uEORpPcIQWHcD8scQf8hWyCQrqbqD9ZTQdK1ghlao="
    - secure: "E7/pAsztbZF+lrE7zwwYL6npd5Py//4990LiWynRCIX8MBSRp7ffpRSpkmF1IsUNXYOGnDByLnZwL/FkogJXc8/Da5kq93zuzm1ymTM1hDF4p3Zc5iWZfK82Af8UdZTcNgf69/fG4lOOTDjhw0dqV6bOkXCohgm9K3WdsBX8w74="
  matrix:
    - SELENIUM_BROWSER=builder1
    - SELENIUM_BROWSER=builder2
    - SELENIUM_BROWSER=builder3
    - SELENIUM_BROWSER=chrome
    - SELENIUM_BROWSER=ie
    - SELENIUM_BROWSER=safari
    - SELENIUM_BROWSER=firefox

addons:
  sauce_connect:
    direct_domains: firebase.com,firebaseio.com

before_script:
  - npm install -g gulp
  - npm install
  - export FIREBASE_TOKEN=`cat tools/firebase_token.enc | openssl enc -aes-128-cbc -a -d -salt -pass pass:$FIREBASE_PWD`

script:
  - >
    if [[ $SELENIUM_BROWSER == builder* ]]; then
      travis_stop_sauce_connect
      tools/builder.sh;
    elif [ "$SELENIUM_BROWSER" == "chrome" ]; then
      gulp test --target=tests;
    else
      gulp test --target=tests --filter=-min_js
    fi

notifications:
  email: false
